version: '3.9'

services:
  mysql:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    volumes:
      - ../../data/mysql:/data
    environment:
      - TZ=Asia/Seoul
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}
    networks:
      - local

networks:
  local:
    name: local
